# Deployment
deployment:
  name: nginx
  replicas: 1
  label: nginx
  container_name: nginx
  image: nginx
  port: 80

# Service
service:
  name: nginx-svc
  protocl: http
  port: 80
  label: nginx
  type: NodePort