apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
spec:
  replicas: 1 # always one copy of below pod template should run 
  selector:
    matchLabels:
      app: ecomm
  template: # pod template
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: ravi2krishna/ecomm
        ports:
        - containerPort: 80