apiVersion: v1
kind: Pod
metadata:
  name: multi-pod-new
spec:
  containers:
  - name: n1
    image: nginx
    ports:
    - containerPort: 80
  - name: n2
    image: ravi2krishna/nodejs-api
    ports:
    - containerPort: 8080