apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: n1
    image: nginx
    ports:
    - containerPort: 80
  - name: n2
    image: nginx
    ports:
    - containerPort: 80