kind: Service
apiVersion: v1
metadata:
  name: {{.Values.service.name}}
spec:
  ports:
    - name: {{.Values.service.protocl}}
      port: {{.Values.service.port}}
  selector:
    app: {{.Values.service.label}}
  type: {{.Values.service.type}}